### ISSUE TITLE
Removal of AS211380

### ISSUE THREAD

**Issue by ghost** [Bogons-DFZ-Zone/Public-Lists#1]
I am a representative of AS211380, and we would appreciate it if you removed our AS from this list, as there is no valid reason for our inclusion.

**Comment by ghost** [comment]
Please merge: https://github.com/Bogons-DFZ-Zone/Public-Lists/pull/2

**Comment by CloudieLLC** [comment]
As this is a list, that is used by multiple users, that was also requested to be made public by other users to utilize. 
The users in question, don't have to have reason to block AS211380. But, it may have something to do with your past actions. for example, looking in the list, there are people that have participated in DDoS for Hire, there have been people which have Hijacked IP space, as well as people known to have falsified business documents, there's been people that are just.. people. But anybody on the Internet is able to reject any prefix they want. and anyone that utilizes a list like this should do their own research on the contents of the list themselves.
